(() => {
"use strict";
const model=window.LifeTrackerMigrationV4;
if(!model) throw new Error("migration-v4.js must load before daybook.js");
const STORE="lifeTrackerData.v4", PHOTO_DB="habitAppTestPhotosV1", PHOTO_STORE="photos";
const $=id=>document.getElementById(id);
const RU={
ai_engineering:["Развивать технические навыки для Analytics Engineering, Data/AI Solutions и AI Automation.","Хотя бы ~15 минут конкретного прогресса: AI API, Python, агент, MCP, RAG, eval, Cloud Run AI-сервис, интеграция данных/AI, технический эксперимент или чтение с конкретной заметкой о применении.","Примерно 45–90+ минут содержательной работы над проектом или завершённый технический результат."],
metaforge_product:["Развивать реальный опыт продукта, роста и данных вне основной зарплатной работы.","Один конкретный шаг: полезный вопрос разработчикам, гипотеза измерения, идея по воронке, аналитический запрос, оформленная продуктовая идея, задача внедрения или содержательное обсуждение.","Существенный прогресс: аудит аналитики, анализ воронки, дизайн tracking, dashboard/data model, предложение эксперимента, внедрение, работа над case study или измеримый продуктовый результат."],
trading_investing:["Относиться к трейдингу как к дисциплинированному эксперименту, а не развлечению или азартной игре; не терять из вида долгосрочные инвестиции.","Анализ трейда, журнал, review позиции или checklist сетапа; либо review портфеля/аллокации, плановая инвестиция или обновление инвестиционного плана. Сам факт сделки не считается.","Трейдинг: анализ + сетап + checklist + риск/stop + журнал (+ post-analysis, когда применимо); либо содержательное запланированное инвестиционное действие/review."],
career_income:["Повышать профессиональную рыночную ценность и не застревать в комфортной текущей роли.","Одно небольшое конкретное карьерное действие: посмотреть вакансию, улучшить CV/LinkedIn, связаться с человеком, зафиксировать достижение или продвинуть важную карьерную задачу.","Значимый результат: отклик, интервью, существенное обновление CV/portfolio, важное достижение на текущей работе, разговор о зарплате/карьере или возможность внешнего дохода."],
body_nutrition:["Здоровье, физическое состояние и ежедневная энергия.","Осмысленная физическая активность и достаточно контролируемое питание.","Хорошая тренировка/активность плюс в целом качественное питание."],
son_connection:["Поддерживать стабильную связь отец–сын несмотря на расстояние.","5–10 минут звонка/видеосвязи, голосовое сообщение, фото, короткий содержательный обмен, вопрос о его дне или рассказ о папином дне.","Более длинное качественное общение, совместная онлайн-активность, планирование/подготовка следующей встречи, содержательная удалённая активность или настоящее качественное время вместе."],
people_contact:["Не позволять жизни превращаться только в работу, спортзал, компьютер и телевизор.","Один содержательный контакт с человеком: настоящий звонок, разговор, кофе, прогулка, встреча, социальная активность или качественное общение с коллегой/другом/семьёй.","Существенный живой/социальный опыт, который дал энергию или чувство связи."],
money:["Поддерживать свободу осознанным контролем cash flow, а не навязчивой экономией на мелочах.","Записать/проверить расходы, избежать очевидной импульсивной покупки или проверить предстоящие траты.","Планирование расходов, review бюджета/cash flow, распределение сбережений или осознанно принятое более крупное финансовое решение."],
recovery_tomorrow:["Правильно завершать сегодняшний день и уменьшать трение для завтрашнего.","Подготовить или проверить план на завтра, сделать базовую подготовку и принять разумное решение о времени сна/восстановлении.","Завтра спланировано, полезная подготовка сделана, целевое время сна соблюдено и восстановление получилось."],
life_experience:["Строить интересную жизнь вместо автоматического ухода в пассивный комфорт.","Один осознанный опыт вне рутины: новый маршрут/прогулка, велосипед, кино, кафе, культурное событие, плавание, новое место, активность, встреча или небольшая поездка. Пассивное развлечение дома не считается.","Более существенный опыт: мини-путешествие, концерт, театр, событие, новый город/место, значимая активность или что-то, что хочется запомнить."]
};
function upgrade(data){if(!data||!Array.isArray(data.habits))return data;for(const h of data.habits){const r=RU[h?.id];if(!r||h.definitionSetId!=="life_v4")continue;h.description=r[0];h.minDescription=h.min=r[1];h.doneDescription=r[2];}data.settings=data.settings||{};data.settings.visibleMetrics=["general","sleep","energy","stress"];return data;}
const n0=model.normalizeV4.bind(model),m0=model.migrateV3ToV4.bind(model),l0=model.loadOrMigrateStorage.bind(model);
model.normalizeV4=s=>upgrade(n0(s)); model.migrateV3ToV4=s=>upgrade(m0(s));
model.loadOrMigrateStorage=storage=>{const d=l0(storage);if(!d)return d;upgrade(d);for(const [date,e] of Object.entries(d.entries||{})){if(date>="2026-08-13"&&e?.metrics){const n=Number(e.metrics.general);if(e.metrics.general!==""&&Number.isFinite(n)&&n>5&&n<=10)e.metrics.general=String(Math.round(n/2*10)/10);}}storage.setItem(STORE,JSON.stringify(d));return d;};
const df0=model.definitionsForDate.bind(model);
model.definitionsForDate=(data,date)=>{const base=df0(data,date),entry=data?.entries?.[date];if(!entry?.habits)return base;const seen=new Set(base.map(h=>h.id));const extras=(data.habits||[]).filter(h=>h?.definitionSetId==="legacy_v3"&&h.endDate&&date>h.endDate).filter(h=>{const r=entry.habits[h.id];return r&&[r.status,r.comment,r.notes].some(v=>v!=null&&String(v).trim()!=="");}).filter(h=>!seen.has(h.id)).map(h=>({...h,name:`Legacy carryover · ${h.name}`}));return [...base,...extras];};
function date(){return $("dateInput")?.value||new Date().toISOString().slice(0,10)}
function addDate(v,n){const d=new Date(v+"T12:00:00");d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function read(){try{const s=localStorage.getItem(STORE);return s?JSON.parse(s):null}catch{return null}}
function write(d){localStorage.setItem(STORE,JSON.stringify(d))}
function entry(d,dt){d.entries=d.entries||{};return d.entries[dt]||(d.entries[dt]={date:dt,metrics:{},habits:{},dayNote:"",updatedAt:null})}
function css(){const s=document.createElement("style");s.textContent=`
.habitDescription{white-space:pre-wrap!important;overflow:visible!important;color:var(--muted)}
.planTask{border:1px solid var(--line);border-radius:14px;padding:10px;background:#0f1628;margin-top:9px}.planTask.done{opacity:.72}.planTask.done .taskText{text-decoration:line-through}
.taskMain{display:grid;grid-template-columns:auto minmax(0,1fr);gap:9px;align-items:center}.taskCheck{width:24px;height:24px;margin:0;accent-color:#34d399}.taskFooter{display:flex;gap:8px;align-items:end;margin-top:8px}.taskFooter label{flex:1;margin:0}.taskTomorrow{width:38px;min-width:38px;padding:6px;font-size:18px}
#photoPreviewWrap{height:33vh;min-height:190px;max-height:360px;display:flex;align-items:center;justify-content:center;cursor:zoom-in}#photoPreviewWrap.hidden{display:none!important}#photoPreviewWrap img{width:100%;height:100%;object-fit:contain}
#photoFullscreen{position:fixed;inset:0;z-index:9999;background:#000;display:flex;align-items:center;justify-content:center}#photoFullscreen.hidden{display:none!important}#photoFullscreen img{width:100%;height:100%;object-fit:contain}#photoFullscreen button{position:absolute;right:12px;top:calc(12px + env(safe-area-inset-top));z-index:2}
.calendarDay{position:relative;overflow:hidden!important}.calFill{position:absolute;inset:0;z-index:0}.calInner{position:relative;z-index:1;height:100%;width:100%;display:flex;flex-direction:column;align-items:flex-start;justify-content:space-between}.calSummary{font-size:9px;line-height:1.25;text-align:left;color:#fff;text-shadow:0 1px 2px #000}
@media(max-width:520px){#photoPreviewWrap{height:32vh;min-height:180px}.calendarDay{min-height:68px!important}}`;document.head.appendChild(s)}
function descriptions(){const d=read();if(!d)return;const defs=model.definitionsForDate(d,date());const map=new Map(defs.map(x=>[x.name,x]));for(const card of document.querySelectorAll("#habits .habit")){const n=card.querySelector(".habitName")?.textContent.replace(/^\d+\.\s*/,"");const h=map.get(n)||defs.find(x=>n?.endsWith(x.name));const box=card.querySelector(".habitMin");if(box&&h){box.textContent=h.description||"";box.classList.add("habitDescription")}}}
function planCard(){if($("dayPlanCard"))return;const first=document.querySelector("#tab-today > .card");if(!first)return;const c=document.createElement("div");c.id="dayPlanCard";c.className="card";c.innerHTML=`<div class="sectionTitle"><h2>План на день</h2><button id="copyPlanTomorrow" type="button">План → завтра</button></div><label for="planNote">Фокус / общий план</label><textarea id="planNote" class="planNote" placeholder="План только для выбранного дня"></textarea><div class="planAddRow topSpace"><input id="newPlanTask" type="text" placeholder="Новая задача"><button id="addPlanTask" class="btnGood" type="button">＋</button></div><div id="planTasks"></div>`;first.after(c);$("planNote").onchange=savePlan;$("addPlanTask").onclick=addTask;$("newPlanTask").onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();addTask()}};$("copyPlanTomorrow").onclick=copyPlan}
function savePlan(){const d=read();if(!d)return;const e=entry(d,date());e.planNote=$("planNote").value||"";e.updatedAt=new Date().toISOString();write(d)}
function addTask(){const i=$("newPlanTask"),text=i?.value.trim();if(!text)return i?.focus();const d=read();if(!d)return;const e=entry(d,date());e.planTasks=Array.isArray(e.planTasks)?e.planTasks:[];e.planTasks.push({id:`task_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,text,done:false,continuationOf:"",createdAt:new Date().toISOString()});e.updatedAt=new Date().toISOString();write(d);i.value="";renderPlan()}
function updTask(id,p){const d=read(),e=d&&entry(d,date()),t=e?.planTasks?.find(x=>x.id===id);if(!t)return;Object.assign(t,p);e.updatedAt=new Date().toISOString();write(d)}
function prevSelect(d,dt,t){const s=document.createElement("select"),n=document.createElement("option");n.value="";n.textContent="— не связано —";s.append(n);Object.keys(d.entries||{}).filter(x=>x<dt&&x>=addDate(dt,-60)).sort().reverse().forEach(x=>(d.entries[x]?.planTasks||[]).forEach(p=>{if(!p?.text)return;const o=document.createElement("option");o.value=`${x}|${p.id}`;o.textContent=`${x} · ${p.text}${p.done?" ✓":""}`;o.selected=o.value===(t.continuationOf||"");s.append(o)}));return s}
function copyTask(id){const d=read(),dt=date(),src=d?.entries?.[dt]?.planTasks?.find(x=>x.id===id);if(!src)return;const nd=addDate(dt,1),e=entry(d,nd);e.planTasks=Array.isArray(e.planTasks)?e.planTasks:[];const link=`${dt}|${src.id}`;if(e.planTasks.some(x=>x.continuationOf===link))return;e.planTasks.push({id:`task_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,text:src.text,done:false,continuationOf:link,createdAt:new Date().toISOString()});e.updatedAt=new Date().toISOString();write(d)}
function copyPlan(){const text=$("planNote")?.value||"";if(!text.trim())return;const d=read();if(!d)return;const e=entry(d,addDate(date(),1));e.planNote=text;e.updatedAt=new Date().toISOString();write(d)}
function renderPlan(){planCard();const d=read(),dt=date(),e=d?.entries?.[dt]||{},box=$("planTasks"),note=$("planNote");if(!box||!note)return;note.value=e.planNote||"";box.innerHTML="";for(const t of (Array.isArray(e.planTasks)?e.planTasks:[])){const r=document.createElement("div");r.className=`planTask ${t.done?"done":""}`;const m=document.createElement("div");m.className="taskMain";const ch=document.createElement("input");ch.type="checkbox";ch.className="taskCheck";ch.checked=!!t.done;ch.onchange=()=>{updTask(t.id,{done:ch.checked});r.classList.toggle("done",ch.checked)};const tx=document.createElement("input");tx.className="taskText";tx.value=t.text||"";tx.onchange=()=>updTask(t.id,{text:tx.value.trim()});m.append(ch,tx);const f=document.createElement("div");f.className="taskFooter";const l=document.createElement("label");l.className="small";l.textContent="Продолжает:";const s=prevSelect(d,dt,t);s.onchange=()=>updTask(t.id,{continuationOf:s.value});l.append(s);const b=document.createElement("button");b.type="button";b.className="taskTomorrow";b.textContent="↪";b.title="Перенести только эту задачу на завтра";b.onclick=()=>copyTask(t.id);f.append(l,b);r.append(m,f);box.append(r)}}
function openDb(){return new Promise((res,rej)=>{const q=indexedDB.open(PHOTO_DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(PHOTO_STORE))q.result.createObjectStore(PHOTO_STORE,{keyPath:"date"})};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function getPhoto(dt){const db=await openDb();return new Promise((res,rej)=>{const q=db.transaction(PHOTO_STORE,"readonly").objectStore(PHOTO_STORE).get(dt);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)})}
async function putPhoto(r){const db=await openDb();return new Promise((res,rej)=>{const t=db.transaction(PHOTO_STORE,"readwrite");t.objectStore(PHOTO_STORE).put(r);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
function dataUrl(b){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result||""));r.onerror=()=>rej(r.error);r.readAsDataURL(b)})}
function photoCard(){if($("photoDayCard"))return;planCard();const p=$("dayPlanCard");if(!p)return;const c=document.createElement("div");c.id="photoDayCard";c.className="card";c.innerHTML=`<div class="sectionTitle"><h2>Photo of the Day</h2><span id="photoStatus" class="pill">нет фото</span></div><div id="photoPreviewWrap" class="photoPreviewWrap hidden"><img id="photoPreview" alt="Photo of the Day"></div><input id="photoInput" class="fileInput" type="file" accept="image/*"><div class="hint topSpace">Одно фото на день. Новое фото заменяет предыдущее.</div>`;p.after(c);$("photoInput").onchange=savePhoto;$("photoPreviewWrap").onclick=fullPhoto}
function fullModal(){if($("photoFullscreen"))return;const m=document.createElement("div");m.id="photoFullscreen";m.className="hidden";m.innerHTML=`<img id="photoFullscreenImg"><button type="button">✕</button>`;document.body.append(m);m.querySelector("button").onclick=()=>m.classList.add("hidden");m.onclick=e=>{if(e.target===m)m.classList.add("hidden")}}
function fullPhoto(){const src=$("photoPreview")?.src;if(!src)return;fullModal();$("photoFullscreenImg").src=src;$("photoFullscreen").classList.remove("hidden")}
async function renderPhoto(){photoCard();fullModal();const w=$("photoPreviewWrap"),im=$("photoPreview"),st=$("photoStatus");if(!w||!im)return;const r=await getPhoto(date()).catch(()=>null);if(!r?.blob){w.classList.add("hidden");im.removeAttribute("src");if(st)st.textContent="нет фото";return}im.src=await dataUrl(r.blob);w.classList.remove("hidden");if(st)st.textContent="фото"}
async function savePhoto(ev){const f=ev.target.files?.[0];if(!f)return;const dt=date();await putPhoto({date:dt,blob:f,name:f.name||`photo-${dt}`,type:f.type||"",size:f.size||0,updatedAt:new Date().toISOString()});const d=read();if(d){const e=entry(d,dt);e.photo={present:true,name:f.name||"",type:f.type||"",size:f.size||0,updatedAt:new Date().toISOString()};e.updatedAt=new Date().toISOString();write(d)}ev.target.value="";await renderPhoto()}
function calendar(){if(document.querySelector('[data-tab="calendar"]'))return;const tabs=document.querySelector(".tabs"),main=document.querySelector("main");if(!tabs||!main)return;const b=document.createElement("button");b.type="button";b.dataset.tab="calendar";b.textContent="Calendar";tabs.append(b);const s=document.createElement("section");s.id="tab-calendar";s.className="hidden";s.innerHTML=`<div class="card"><div class="sectionTitle"><button id="calendarPrev">‹</button><input id="calendarMonth" type="month"><button id="calendarNext">›</button></div><div class="calendarWeekdays"><span>Пн</span><span>Вт</span><span>Ср</span><span>Чт</span><span>Пт</span><span>Сб</span><span>Вс</span></div><div id="calendarGrid" class="calendarGrid"></div></div>`;main.append(s);b.onclick=showCal;$("calendarPrev").onclick=()=>shiftCal(-1);$("calendarNext").onclick=()=>shiftCal(1);$("calendarMonth").onchange=renderCal;document.querySelectorAll('.tabs button:not([data-tab="calendar"])').forEach(x=>x.addEventListener("click",()=>s.classList.add("hidden")))}
function showCal(){document.querySelectorAll(".tabs button").forEach(x=>x.classList.toggle("active",x.dataset.tab==="calendar"));["today","progress","export","settings"].forEach(n=>$("tab-"+n)?.classList.add("hidden"));$("tab-calendar")?.classList.remove("hidden");if(!$("calendarMonth").value)$("calendarMonth").value=date().slice(0,7);renderCal()}
function shiftCal(n){const i=$("calendarMonth"),[y,m]=(i.value||date().slice(0,7)).split("-").map(Number),d=new Date(y,m-1+n,1);i.value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;renderCal()}
function sum(d,dt){const defs=model.definitionsForDate(d,dt),e=d.entries?.[dt]||{};let done=0,min=0;defs.forEach(h=>{const s=e.habits?.[h.id]?.status||"";if(s==="done")done++;else if(s==="min")min++});return{done,min,total:Math.max(defs.length,1),g:e.metrics?.general??""}}
function renderCal(){const g=$("calendarGrid"),i=$("calendarMonth");if(!g||!i)return;if(!i.value)i.value=date().slice(0,7);const[y,m]=i.value.split("-").map(Number),days=new Date(y,m,0).getDate(),off=(new Date(y,m-1,1).getDay()+6)%7,d=read()||{entries:{},habits:[]};g.innerHTML="";for(let x=0;x<off;x++){const z=document.createElement("div");z.className="calendarBlank";g.append(z)}for(let day=1;day<=days;day++){const dt=`${y}-${String(m).padStart(2,"0")}-${String(day).padStart(2,"0")}`,s=sum(d,dt),de=Math.round(s.done/s.total*100),me=Math.min(100,de+Math.round(s.min/s.total*100)),b=document.createElement("button");b.type="button";b.className=`calendarDay ${dt===date()?"calendarSelected":""}`;b.innerHTML=`<div class="calFill"></div><div class="calInner"><strong>${day}</strong><div class="calSummary"><div>G ${s.g===""?"–":s.g}</div><div>✓ ${s.done} · MIN ${s.min}</div></div></div>`;b.querySelector(".calFill").style.background=`linear-gradient(to top,rgba(5,150,105,.72) 0%,rgba(5,150,105,.72) ${de}%,rgba(217,119,6,.70) ${de}%,rgba(217,119,6,.70) ${me}%,rgba(15,22,40,.04) ${me}%,rgba(15,22,40,.04) 100%)`;b.onclick=()=>{$("dateInput").value=dt;$("dateInput").dispatchEvent(new Event("change",{bubbles:true}));document.querySelector('[data-tab="today"]')?.click()};g.append(b)}}
function refresh(){renderPlan();renderPhoto();setTimeout(descriptions,0)}
function init(){css();document.querySelector('[data-tab="today"]').textContent="Daybook";planCard();photoCard();calendar();fullModal();refresh();const h=$("habits");if(h)new MutationObserver(()=>setTimeout(descriptions,0)).observe(h,{childList:true});$("dateInput")?.addEventListener("change",()=>setTimeout(refresh,0));["prevDay","nextDay"].forEach(id=>$(id)?.addEventListener("click",()=>setTimeout(refresh,0)));document.querySelector('[data-tab="today"]')?.addEventListener("click",()=>setTimeout(refresh,0))}
document.addEventListener("DOMContentLoaded",()=>setTimeout(init,0));
})();